name: build

on:
  push:
    branches:
      - master

jobs:
  webpage:
    runs-on: ubuntu-20.04
  steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby rake docutils-common

    - name: Build page and manual
      run: |
        rake travis
