name: build

on:
  push:
    branches:
      - master
      - switch_to_github_workflow

jobs:
  webpage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check out build results repository
        uses: actions/checkout@v2
        with:
          repository: mpv-player/mpv-player.github.io
          ref: master
          path: build
          fetch-depth: 0

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docutils-common

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.1"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build site and manual
        run: |
          rake travis
          pushd build
          /usr/bin/git remote add github https://github.com/jeeb/mpv.io
          git push -u github HEAD:le_ci_build -f
          popd
